FROM ubuntu:18.04
WORKDIR /opt/CTFd
RUN mkdir -p /opt/CTFd /var/log/CTFd /var/uploads

COPY sources.list /etc/apt/
# hadolint ignore=DL3008

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        default-mysql-client \
        python-dev \
        libffi-dev \
        libssl-dev \
        git\
	python3 \
	python3-pip \
	vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . /opt/CTFd


RUN pip3 install -r requirements.txt --no-cache-dir
# hadolint ignore=SC2086
RUN for d in CTFd/plugins/*; do \
        if [ -f "$d/requirements.txt" ]; then \
            pip3 install -r $d/requirements.txt --no-cache-dir; \
        fi; \
    done;

RUN adduser \
    -u 0 \
    --gecos "" \
    --shell /bin/bash \
    -p ****** \
    ctfd
RUN chmod +x /opt/CTFd/docker-entrypoint.sh \
    && chown -R 0:0 /opt/CTFd /var/log/CTFd /var/uploads

USER 0
EXPOSE 8000
ENTRYPOINT ["/opt/CTFd/docker-entrypoint.sh"]
